version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back_end:/app/laravel-app
      - ./front_end/build:/app/react-app/build
      - ./ai_server:/app/flask-app
